compile the latest version of libvmi: uses cmake instead of autogen
Wenzel/vagrant-xen-pyvmidbg pull request #2
Opened 2019-03-14 17:43 UTC by sh286

2019-03-14 22:52 UTC, Wenzel requested changes

2019-03-14 22:52 UTC, Wenzel commented on ubuntu/provision/libvmi.yml
> +    - cmake
you can remove `automake`  as a dependency

2019-03-14 22:52 UTC, Wenzel commented on ubuntu/provision/libvmi.yml
> +  command: mkdir build
if you want to be full Ansibile, use the file module:
~~~YAML
name: create build directory
file:
  path: /home/vagrant/libvmi/build
  state: directory
~~~

something like that, check the file module

2019-03-15 05:29 UTC, sh286 commented
@Wenzel all done

2019-03-15 09:29 UTC, Wenzel approved these changes

2019-03-15 09:30 UTC, merged